"""Call identity — mandatory keys propagated to all logs, events and metrics."""

from __future__ import annotations

from dataclasses import dataclass, asdict


@dataclass(frozen=True)
class CallIdentity:
    vmo_call_id: str           # UUID v4 generated by vmo_pipecat at StasisStart
    asterisk_channel_id: str    # event.channel.id of the caller channel
    call_id_sbc: str            # X-CALL-ID-SBC SIP header
    tenant_id: str              # X-TENANT-ID SIP header
    tenant_name: str            # CHANNEL(tenant_name) — set by dialplan per trunk
    node_id: str                # _vmo_node_id injected by ARIPool
    did: str                    # ${EXTEN} — DID dialled into Asterisk
    caller_id: str = ""         # CHANNEL(caller_id) — caller number from dialplan

    def asdict(self) -> dict:
        return asdict(self)
