[general]
type = global
user_agent = empatIA

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060
external_media_address = 192.168.10.92
external_signaling_address = 192.168.10.92
local_net = 172.18.0.0/24

[9999]
type = endpoint
context = extensiones-test
disallow = all
allow = ulaw
auth = 9999
aors = 9999
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
ice_support = no
media_use_received_transport = no

[9999]
type = auth
auth_type = userpass
username = 9999
password = 9999

[9999]
type = aor
max_contacts = 2
remove_existing = yes

[9998]
type = endpoint
context = extensiones-test
disallow = all
allow = ulaw
auth = 9998
aors = 9998
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
ice_support = no
media_use_received_transport = no

[9998]
type = auth
auth_type = userpass
username = 9998
password = 9999

[9998]
type = aor
max_contacts = 2
remove_existing = yes

[9997]
type = endpoint
context = extensiones-test
disallow = all
allow = ulaw
auth = 9997
aors = 9997
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
ice_support = no
media_use_received_transport = no

[9997]
type = auth
auth_type = userpass
username = 9997
password = 9999

[9997]
type = aor
max_contacts = 2
remove_existing = yes